begin;

create table if not exists public.chat_ai_product_keys (
  product_code text,
  product_name text primary key,
  type text,
  c1 text,
  c2 text,
  size text,
  label2 text,
  form text,
  color text,
  volume text,
  variant text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.chat_ai_product_keys enable row level security;
revoke all on public.chat_ai_product_keys from public, anon, authenticated;

insert into public.chat_ai_product_keys(
  product_code,product_name,type,c1,c2,size,label2,form,color,volume,variant
) values
('SUA-000001','Sua 9 hat','Sữa','9','hat',null,null,null,null,null,null),
('SUA-000002','Sua 9 hat cao dam','Sữa','9','hat',null,null,null,null,null,'cao dam'),
('SUA-000003','Sua adm be','Sữa','adm',null,'be',null,null,null,null,null),
('SUA-000004','Sua bo be co','Sữa','bo',null,'bé, 110',null,null,null,null,'có, có đường'),
('SUA-000005','Sua bo be it','Sữa','bo',null,'bé, 110',null,null,null,null,'ít, ít đường'),
('SUA-000006','Sua bo bich co','Sữa','bo',null,null,null,'bich',null,null,'có, có đường'),
('SUA-000010','Sua bo bich dau','Sữa','bo',null,null,null,'bich',null,null,'dau'),
('SUA-000007','Sua bo bich it','Sữa','bo',null,null,null,'bich',null,null,'ít, ít đường'),
('SUA-000008','Sua bo bich khong','Sữa','bo',null,null,null,'bich',null,null,'không, không đường'),
('SUA-000009','Sua bo bich so','Sữa','bo',null,null,null,'bich',null,null,'so'),
('SUA-000011','Sua bo lit co','Sữa','bo',null,null,null,'lit',null,null,'có, có đường'),
('SUA-000012','Sua bo lit it','Sữa','bo',null,null,null,'lit',null,null,'ít, ít đường'),
('SUA-000013','Sua bo lit khong','Sữa','bo',null,null,null,'lit',null,null,'không, không đường'),
('SUA-000014','Sua bo to co','Sữa','bo',null,'to, 180',null,null,null,null,'có, có đường'),
('SUA-000015','Sua bo to it','Sữa','bo',null,'to, 180',null,null,null,null,'ít, ít đường'),
('SUA-000016','Sua bo to khong','Sữa','bo',null,'to, 180',null,null,null,null,'không, không đường'),
('SUA-000017','Sua chua co','Sữa','chua',null,null,null,null,null,null,'có, có đường'),
('SUA-000018','Sua chua duong den','Sữa','chua',null,null,null,null,null,null,'duong den'),
('SUA-000019','Sua chua greenfram','Sữa','chua',null,null,'greenfram, green, fram',null,null,null,null),
('SUA-000020','Sua chua it','Sữa','chua',null,null,null,null,null,null,'ít, ít đường'),
('SUA-000021','Sua chua khong','Sữa','chua',null,null,null,null,null,null,'không, không đường'),
('SUA-000022','Sua chua nep cam','Sữa','chua',null,null,null,null,null,null,'nep cam'),
('SUA-000023','Sua chua nha dam co','Sữa','chua',null,null,'nha dam, nha, dam',null,null,null,'có, có đường'),
('SUA-000024','Sua chua nha dam it','Sữa','chua',null,null,'nha dam, nha, dam',null,null,null,'ít, ít đường'),
('SUA-000025','Sua chua star trang','Sữa','chua',null,null,'star',null,'trang',null,null),
('SUA-000026','Sua chua trai cay','Sữa','chua',null,null,null,null,null,null,'trai cay'),
('SUA-000027','Sua dac tai loc 1284','Sữa','dac',null,null,'tai loc, tai, loc',null,null,'1284',null),
('SUA-000028','Sua gau xanh vnm','Sữa','gau',null,null,null,null,'xanh',null,null),
('SUA-000029','Sua green cao dam','Sữa','green',null,null,null,null,null,null,'cao dam'),
('SUA-000030','Sua green fram be co 110ml','Sữa','green','fram','bé, 110',null,null,null,null,'có, có đường'),
('SUA-000031','Sua green fram be it 110ml','Sữa','green','fram','bé, 110',null,null,null,null,'ít, ít đường'),
('SUA-000032','Sua green fram to co 180ml','Sữa','green','fram','to, 180',null,null,null,null,'có, có đường'),
('SUA-000033','Sua green fram to it 180ml','Sữa','green','fram','to, 180',null,null,null,null,'ít, ít đường'),
('SUA-000058','Sua green lit','Sữa','green',null,null,null,'lit',null,null,null),
('SUA-000034','Sua ngoi sao dat','Sữa','ngoi','sao',null,null,null,null,null,'đắt, xanh lá'),
('SUA-000035','Sua ngoi sao re','Sữa','ngoi','sao',null,null,null,null,null,'rẻ, xanh đậm'),
('SUA-000036','Sua op vang vnm','Sữa','op',null,null,null,null,'vang',null,null),
('SUA-000037','Sua probi be mau - dâu','Sữa','probi, bi, proby',null,'be','mau',null,null,null,'dâu'),
('SUA-000038','Sua probi be mau - dứa','Sữa','probi, bi, proby',null,'be','mau',null,null,null,'dứa'),
('SUA-000039','Sua probi be mau - dưa gang','Sữa','probi, bi, proby',null,'be','mau',null,null,null,'dưa gang, dưa'),
('SUA-000040','Sua probi be mau - it','Sữa','probi, bi, proby',null,'be','mau',null,null,null,'ít, ít đường'),
('SUA-000041','Sua probi be mau - viet quat','Sữa','probi, bi, proby',null,'be','mau',null,null,null,'viet quat'),
('SUA-000042','Sua probi be trang','Sữa','probi, bi, proby',null,'be',null,null,'trắng, có, truyền thống',null,null),
('SUA-000043','Sua probi lo 400ml','Sữa','probi, bi, proby',null,null,null,'lo',null,'400ml',null),
('SUA-000057','Sua probi lo 700ml','Sữa','probi, bi, proby',null,null,null,'lo',null,'700ml',null),
('SUA-000044','Sua probi to mau - dâu','Sữa','probi, bi, proby',null,'to','mau',null,null,null,'dâu'),
('SUA-000045','Sua probi to mau - it','Sữa','probi, bi, proby',null,'to','mau',null,null,null,'ít, ít đường'),
('SUA-000046','Sua probi to mau - viet quat','Sữa','probi, bi, proby',null,'to','mau',null,null,null,'viet quat'),
('SUA-000047','Sua probi to trang','Sữa','probi, bi, proby',null,'to',null,null,'trắng, có, truyền thống',null,null),
('SUA-000048','Sua su lo cam','Sữa','su',null,null,null,'lo',null,null,'cam'),
('SUA-000049','Sua su lo dau','Sữa','su',null,null,null,'lo',null,null,'dau'),
('SUA-000050','Sua tho do giay 1284g','Sữa','tho',null,null,'do','giay',null,'1284g, 1,2kg',null),
('SUA-000051','Sua tho do giay 1kg','Sữa','tho',null,null,'do','giay',null,'1kg',null),
('SUA-000052','Sua tho do giay 380g','Sữa','tho',null,null,'do','giay',null,'380g',null),
('SUA-000053','Sua tho do sat','Sữa','tho',null,null,'do','sat',null,null,null),
('SUA-000054','Sua tho trang','Sữa','tho',null,null,null,null,'trang',null,null),
('SUA-000055','Sua tho tuyt','Sữa','tho',null,null,null,'tuyt',null,null,null),
('SUA-000056','Sua tho vi','Sữa','tho',null,null,null,'vi',null,null,null)
on conflict(product_name) do update set
  product_code=excluded.product_code,
  type=excluded.type,
  c1=excluded.c1,
  c2=excluded.c2,
  size=excluded.size,
  label2=excluded.label2,
  form=excluded.form,
  color=excluded.color,
  volume=excluded.volume,
  variant=excluded.variant,
  active=true,
  updated_at=now();

commit;
